# Generated by Django 3.1.5 on 2021-01-08 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0002_auto_20210107_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablesmodel',
            old_name='tables',
            new_name='table',
        ),
        migrations.RemoveField(
            model_name='datemodel',
            name='resturentdatemodel',
        ),
        migrations.RemoveField(
            model_name='datemodel',
            name='slots',
        ),
        migrations.RemoveField(
            model_name='ratingmodel',
            name='restaurantsratingmodel',
        ),
        migrations.AddField(
            model_name='datemodel',
            name='restaurant_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_date', to='restaurants.restaurantmodel'),
        ),
        migrations.AddField(
            model_name='ratingmodel',
            name='restaurant_rating',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_rating', to='restaurants.restaurantmodel'),
        ),
        migrations.AddField(
            model_name='restaurantmodel',
            name='tables',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tablesmodel',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_time', to='restaurants.timeslotsmodel'),
        ),
        migrations.AddField(
            model_name='timeslotsmodel',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.datemodel'),
        ),
        migrations.AlterField(
            model_name='datemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
