# Generated by Django 3.1.5 on 2021-01-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20210108_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmodel',
            name='ratings',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
