# Generated by Django 3.1.5 on 2021-01-08 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurantmodel_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslotsmodel',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slotpicker', to='restaurants.datemodel'),
        ),
    ]
