# Generated by Django 3.1.5 on 2021-01-09 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20210108_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslotsmodel',
            old_name='time_slots',
            new_name='slots',
        ),
        migrations.RemoveField(
            model_name='datemodel',
            name='restaurant_date',
        ),
        migrations.AddField(
            model_name='datemodel',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='restaurants.restaurantmodel'),
        ),
    ]
