# Generated by Django 3.1.5 on 2021-01-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20210109_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslotsmodel',
            name='slots',
            field=models.IntegerField(max_length=50),
        ),
    ]
